a=int(input("Enter 1st Number")
b=int(input("Enter 2nd Number")
print("Bitwise AND",a&b)
print("Bitwise OR",a|b)
print("Bitwise XOR",a^b)  
print("Bitwise NOT",~b)  
print("Bitwise Left shift",a<<b)
print("Bitwise Right shift",a>>b)       
